analyzer:
  errors:
    invalid_annotation_target: ignore
    no_wildcard_variable_uses: ignore
    prefer_const_constructors: ignore
  plugins:
    - custom_lint

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    avoid_print: false
    prefer_single_quotes: true
    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    avoid_function_literals_in_foreach_calls: false
    sort_child_properties_last: false
    curly_braces_in_flow_control_structures: false

custom_lint:
  enable_all_lint_rules: true