have_fun: false
ignore_patterns:
  - "**/*.freezed.dart"
  - "**/*.g.dart"
  - "**/*.gr.dart"
  - "**/generated/**"
  - "**/.dart_tool/**"
  - "**/build/**"
  - "**/*.mocks.dart"
  - "**/*.config.dart"
  - "**/flutter_export_environment.sh"
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true